--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/gigantessbeta/MoneyLevel
branches:
- master
projects:
  MoneyLevel:
    path: "https://raw.githubusercontent.com/gigantessbeta/MoneyLevel/master/images/image.jpg"
...
