name: MoneyLevel
api: ["5.0.0"]
main: net\mydeacy\moneylevel\MoneyLevelPlugin
version: 3.0.0
author: MyDeacy
depend: ["EconomyAPI"]
load: STARTUP
description: "Economy level plugin"
commands:
  lvup:
    description: "Level up!"
    usage: "/lvup {amount}"
    permission: moneylevel.lvup
  viewlv:
    description: "view level"
    usage: "/viewlv {target}"
    permission: moneylevel.viewlv
  toplv:
    description: "Level Ranking"
    usage: "/toplv {page}"
    permission: moneylevel.toplv
  lvhelp:
    description: "MoneyLevel's help"
    usage: "/lvhelp"
    permission: moneylevel.lvhelp
  setlv:
    description: "Set Level"
    usage: "/setlv {target} {amount}"
    permission: moneylevel.setlv

permissions:
  moneylevel.lvup:
    default: true
  moneylevel.viewlv:
    default: true
  moneylevel.toplv:
    default: true
  moneylevel.lvhelp:
    default: true
  moneylevel.setlv:
    default: op
  moneylevel.*:
    default: op
